# Generated by Django 3.2.20 on 2023-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikidocument_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
