# Generated by Django 3.2.20 on 2023-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20230728_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidocument',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='image URL'),
        ),
    ]
